export const columns = [
  { field: 'id', headerName: 'ID', width: 90 },
	{
		field: 'fieldNo',
		headerName: 'Field no.',
		width: 100,
		editable: true,
	},
	{
		field: 'startTime',
		headerName: 'Start Time',
		// type: 'dateTime',
		width: 150,
		editable: true,
	},
	{
		field: 'curlew',
		headerName: 'Curlew',
		width: 100,
		editable: true,
	},
	{
		field: 'lapwing',
		headerName: 'Lapwing',
		width: 100,
		editable: true,
	},
	{
		field: 'oystercatcherPair',
		headerName: 'Oystercatcher Pair',
		width: 100,
		editable: true,
	},
	{
		field: 'oystercatcherSingle',
		headerName: 'Oystercatcher Single',
		width: 100,
		editable: true,
	},
	{
		field: 'snipeDrumChip',
		headerName: 'Snipe Drum / Chip',
		width: 100,
		editable: true,
	},
	{
		field: 'snipeTotal',
		headerName: 'Snipe Total',
		width: 100,
		editable: true,
	},
	{
		field: 'landUseCode',
		headerName: 'Land Use Code',
		width: 100,
		editable: true,
	},
	{
		field: 'grazed',
		headerName: 'Grazed',
		width: 100,
		editable: true,
	},
	{
		field: 'vegHeight',
		headerName: 'Veg Height',
		width: 100,
		editable: true,
	},
	{
		field: 'fieldWetness',
		headerName: 'Field Wetness',
		width: 100,
		editable: true,
	},
	{
		field: 'standingWater',
		headerName: 'Standing Water',
		width: 100,
		editable: true,
	},
	{
		field: 'du',
		headerName: 'DU',
		width: 25,
		editable: true,
	},
	{
		field: 'su',
		headerName: 'SU',
		width: 25,
		editable: true,
	},
	{
		field: 'mr',
		headerName: 'MR',
		width: 25,
		editable: true,
	},
	{
		field: 'mn',
		headerName: 'MN',
		width: 25,
		editable: true,
	},
	{
		field: 'foxCrow',
		headerName: 'Fox / Crow',
		width: 25,
		editable: true,
	},
	{
		field: 'comments',
		headerName: 'Comments',
		width: 100,
		editable: true,
	},
]